//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LaboratorioJARAF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LABORATORIO_CLINICO_JARAF2Entities : DbContext
    {
        public LABORATORIO_CLINICO_JARAF2Entities()
            : base("name=LABORATORIO_CLINICO_JARAF2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITAS> CITAS { get; set; }
        public virtual DbSet<EXAMENES> EXAMENES { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
